language: java
jdk:
  - openjdk7
  - oraclejdk7
  
before_install:
  - wget -Ojunit.jar http://search.maven.org/remotecontent?filepath=junit/junit/4.11/junit-4.11.jar
  - sed -i 's/^\t<property name="jUnitJar".*/<property name="jUnitJar" location="junit.jar" \/>/g' build.xml